### ISSUE TITLE
sub menu in navigation bar

### ISSUE THREAD

**Issue by ritikarawlani** [WorldHealthOrganization/smart-ig-starter-kit#14]
On the navigation bar there should be ability to view sub-menu/sub-tabs.

**Comment by costateixeira** [comment]
What does this mean? Submenus in the main menu? or something else? 
Can you give an example please?

**Comment by litlfred** [comment]
In the smart-trust repo there is a concepts.html and a bunch of
concepts_xxxx.html.   it would be ideal to have the xxxx pages as sub-items
under the concepts navbar.


Cheers,
-carl

**Comment by costateixeira** [comment]
Is this the goal?
![image](https://github.com/WorldHealthOrganization/smart-ig-starter-kit/assets/16153168/4f15e376-74bd-4580-a88f-90a72efb0ff2)

**Comment by litlfred** [comment]
Yes,!

Cheers,
-carl

**Comment by costateixeira** [comment]
this feature will be in the base template, which will propagate to every IG: 
https://github.com/HL7/ig-template-base/issues/229
